linters:
  enable:
    - gosimple
    - deadcode
    - govet
    - errcheck
    - staticcheck
    - unused
    - structcheck
    - typecheck
    - varcheck
    - revive
    - dupl
    - gocyclo
    - gofmt
    - misspell
    - gocritic
    - goimports
  enable-all: false
  disable-all: true
  fast: false

run:
  timeout: 10m
  skip-dirs-use-default: true
  skip-dirs:
    - 'test'
  tests: false 

linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain 
  gocyclo:
    min-complexity: 30  
  goimports:
  # to run goimports locally to fix this linter issue use this:
  # goimports -w -local="github.com/accurics/terrascan" </path/to/file>
    local-prefixes: "github.com/accurics/terrascan"

output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: tab
  

