name: e2e-vuln-test
on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened, ready_for_review, edited]
jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      GOPATH: /home/runner/work/terrascan
      GOBIN: /home/runner/work/terrascan/bin
      GO_VERSION: 1.16
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_TEST }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_TEST }}
      AWS_REGION: ${{ secrets.AWS_REGION_TEST }}
      AZURE_AUTH_TEST_SECRET:  ${{ secrets.AZURE_AUTH_TEST_SECRET }}
      GOOGLE_APPLICATION_CREDENTIALS_TEST_SECRET:  ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_TEST_KEY }}
    steps:
    - name: Checkout Terrascan
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install golint
      run: go get -u golang.org/x/lint/golint

    - name: Go validations
      run: make validate

    - name: Run e2e tests
      run: make e2e-tests

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

  